version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            ACCEPT_EULA : "Y"
            SA_PASSWORD : "Yukon900"
        ports: 
            - "1433:1433"